apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: backend
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: nginx:1.27
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: APP_ENV

  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {}
      - setWeight: 100