apiVersion: v1
kind: Namespace #tạo namespace để chứa các tài nguyên của ứng dụng web, giúp phân tách và quản lý dễ dàng hơn các resources trong cluster như fe, be
metadata:
  name: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: ConfigMap #lưu trữ cấu hình cho ứng dụng web như port, env vars, database connection strings, giúp tách biệt cấu hình khỏi mã nguồn và dễ dàng cập nhật mà không cần phải xây dựng lại image
metadata:
  name: web-config
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  APP_ENV: "production"
---
apiVersion: apps/v1
kind: Deployment #tạo và quản lý pod cho ứng dụng web như số lượng replica, image, env vars
metadata:
  name: web
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx:1.27
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: web-config
              key: APP_ENV