apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: argo-rollouts
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.37.7

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
    - CreateNamespace=true













# code này cài argo rollout controller vào cluster.
#  Argo Rollouts là một công cụ để quản lý việc triển khai
#   ứng dụng theo cách canary hoặc blue-green, 
#   giúp bạn kiểm soát quá trình triển khai và giảm thiểu 
#   rủi ro khi cập nhật ứng dụng.